package com.example.demo;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.security.Principal;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.client.RestTemplate;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@Controller // This means that that class is a Controller
@RequestMapping(path="/api") // This means URL's start with /api(after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private VacationEntryRepository vacationEntryRepository;

    @GetMapping(path="/me")
    public @ResponseBody User getCurrentUser(Principal principal) {
        if (principal == null) {
            return null;
        }
        return userRepository.findByEmail(principal.getName());
    }

    @DeleteMapping(path="/delete/{id}")
    public @ResponseBody String deleteUser (@PathVariable Integer id) {
        if (!userRepository.existsById(id)) {
            return "Error: User not found";
        }
        
        List<VacationEntry> asParticipant = vacationEntryRepository.findByParticipantId(id);
        vacationEntryRepository.deleteAll(asParticipant);
        
        List<VacationEntry> asTrainer = vacationEntryRepository.findByTrainerId(id);
        vacationEntryRepository.deleteAll(asTrainer);

        userRepository.deleteById(id);
        return "User Deleted";
    }

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email, @RequestParam String role, @RequestParam String password,
            @RequestParam(required = false) Integer assignedTrainerId) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        n.setRole(role);
        n.setPassword(passwordEncoder.encode(password));

        if (assignedTrainerId != null) {
            User trainer = userRepository.findById(assignedTrainerId).orElse(null);
            if (trainer != null) {
                n.setAssignedTrainer(trainer);
            }
        }

        userRepository.save(n);
        return "Saved";
    }

    @PostMapping(path="/updateVacationDays")
    public @ResponseBody String updateVacationDays (@RequestParam Integer userId, @RequestParam Double days) {
        User user = userRepository.findById(userId).orElse(null);
        if (user == null) {
            return "Error: User not found";
        }
        user.setVacationDays(days);
        userRepository.save(user);
        return "Vacation Days Updated";
    }

    @PostMapping(path="/changePassword")
    public @ResponseBody String changePassword (@RequestParam String newPassword, Principal principal) {
        if (principal == null) {
            return "Error: Not logged in";
        }
        User user = userRepository.findByEmail(principal.getName());
        if (user == null) {
            return "Error: User not found";
        }
        user.setPassword(passwordEncoder.encode(newPassword));
        userRepository.save(user);
        return "Password Changed Successfully";
    }

    @GetMapping(path="/usersByTrainer")
    public @ResponseBody Iterable<User> getUsersByTrainer(@RequestParam Integer trainerId) {
        return userRepository.findByAssignedTrainerId(trainerId);
    }

    @PostMapping(path="/addVacation")
    public @ResponseBody String addVacation (@RequestParam String startDate, @RequestParam String endDate,
                                             @RequestParam Integer participantId, @RequestParam Integer trainerId) {
        User participant = userRepository.findById(participantId).orElse(null);
        User trainer = userRepository.findById(trainerId).orElse(null);

        if (participant == null || trainer == null) {
            return "Error: User not found";
        }

        if (!"teilnehmer".equalsIgnoreCase(participant.getRole())) {
            return "Error: Participant must have role 'teilnehmer'";
        }

        if (!"berufstrainer".equalsIgnoreCase(trainer.getRole())) {
            return "Error: Trainer must have role 'berufstrainer'";
        }

        VacationEntry v = new VacationEntry();
        v.setStartDate(java.time.LocalDate.parse(startDate));
        v.setEndDate(java.time.LocalDate.parse(endDate));
        v.setParticipant(participant);
        v.setTrainer(trainer);
        vacationEntryRepository.save(v);
        return "Saved Vacation Entry";
    }

    @PostMapping(path="/requestVacation")
    public @ResponseBody String requestVacation (@RequestParam String startDate, @RequestParam String endDate, Principal principal) {
        if (principal == null) {
            return "Error: Not logged in";
        }
        User participant = userRepository.findByEmail(principal.getName());
        if (participant == null) {
            return "Error: User not found";
        }
        
        User trainer = participant.getAssignedTrainer();
        if (trainer == null) {
            return "Error: No trainer assigned to this participant";
        }

        VacationEntry v = new VacationEntry();
        v.setStartDate(java.time.LocalDate.parse(startDate));
        v.setEndDate(java.time.LocalDate.parse(endDate));
        v.setParticipant(participant);
        v.setTrainer(trainer);
        // Status defaults to "pending"
        vacationEntryRepository.save(v);
        return "Vacation Requested";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/vacationsByUser")
    public @ResponseBody Iterable<VacationEntry> getVacationsByUser(@RequestParam Integer userId) {
        List<VacationEntry> asParticipant = vacationEntryRepository.findByParticipantId(userId);
        List<VacationEntry> asTrainer = vacationEntryRepository.findByTrainerId(userId);

        // Combine both lists
        List<VacationEntry> allVacations = new java.util.ArrayList<>();
        allVacations.addAll(asParticipant);
        allVacations.addAll(asTrainer);

        return allVacations;
    }

    @PostMapping(path="/approveVacation")
    public @ResponseBody String approveVacation (@RequestParam Integer id) {
        VacationEntry v = vacationEntryRepository.findById(id).orElse(null);
        if (v == null) {
            return "Error: Vacation Entry not found";
        }
        
        if ("approved".equals(v.getStatus())) {
            return "Vacation Entry already approved";
        }

        // Calculate working days (excluding weekends and holidays)
        LocalDate start = v.getStartDate();
        LocalDate end = v.getEndDate();
        double workingDays = 0;
        
        if (start != null && end != null) {
            Set<LocalDate> holidays = new HashSet<>();
            try {
                int year = start.getYear();
                String url = "https://get.api-feiertage.de/?years=" + year + "&states=by";
                RestTemplate restTemplate = new RestTemplate();
                String response = restTemplate.getForObject(url, String.class);
                
                ObjectMapper mapper = new ObjectMapper();
                JsonNode root = mapper.readTree(response);
                JsonNode feiertage = root.path("feiertage");
                if (feiertage.isArray()) {
                    for (JsonNode holiday : feiertage) {
                        holidays.add(LocalDate.parse(holiday.path("date").asText()));
                    }
                }
                
                // If end date is in next year, fetch next year's holidays too
                if (end.getYear() > year) {
                     url = "https://get.api-feiertage.de/?years=" + end.getYear() + "&states=by";
                     response = restTemplate.getForObject(url, String.class);
                     root = mapper.readTree(response);
                     feiertage = root.path("feiertage");
                     if (feiertage.isArray()) {
                        for (JsonNode holiday : feiertage) {
                            holidays.add(LocalDate.parse(holiday.path("date").asText()));
                        }
                    }
                }

            } catch (Exception e) {
                e.printStackTrace(); // Log error but continue with weekends logic
            }

            LocalDate current = start;
            while (!current.isAfter(end)) {
                DayOfWeek day = current.getDayOfWeek();
                if (day != DayOfWeek.SATURDAY && day != DayOfWeek.SUNDAY && !holidays.contains(current)) {
                    workingDays++;
                }
                current = current.plusDays(1);
            }
        }

        // Update participant's vacation days
        User participant = v.getParticipant();
        if (participant != null) {
            double currentDays = participant.getVacationDays() != null ? participant.getVacationDays() : 30.0;
            participant.setVacationDays(currentDays - workingDays);
            userRepository.save(participant);
        }

        v.setStatus("approved");
        vacationEntryRepository.save(v);
        return "Vacation Entry Approved";
    }

    @PostMapping(path="/denyVacation")
    public @ResponseBody String denyVacation (@RequestParam Integer id) {
        VacationEntry v = vacationEntryRepository.findById(id).orElse(null);
        if (v == null) {
            return "Error: Vacation Entry not found";
        }
        v.setStatus("denied");
        vacationEntryRepository.save(v);
        return "Vacation Entry Denied";
    }
}